[pytest]
addopts = -s -v
pythonpath = .
testpaths = tests
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = True
markers =
    smoke: Маркировка для smoke тестов.
    functional: Маркировка для функциональных тестов.
    e2e: Маркировка для end-2-end тестов
    regression: Маркировка для регрессионных тестов.
